---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfje/java-test-applications
    tag:        boot-1

inputs:
- name: java-test-applications

outputs:
- name: java-test-applications-built

caches:
- path: gradle

run:
  path: java-test-applications/ci/build.sh
