---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfje/java-test-applications
    tag:        boot-2
    username: ((docker-username))
    password: ((docker-password))

inputs:
- name: java-test-applications

outputs:
- name: java-test-applications-built

caches:
- path: gradle

run:
  path: java-test-applications/ci/build.sh
